### ISSUE TITLE
Improve node status in the overview

### ISSUE THREAD

**Issue by arodrime** [thelastpickle/tlp-dashboards#1]
We currently have 5 charts to show nodes up and down, and it's still not really good from an operator perspective.

![image](https://user-images.githubusercontent.com/1073404/78351813-b5e6a000-75a7-11ea-8d20-a56e43c1e6b0.png)

We need to find a way to improve the usability/visibility on this part.

A lead is to use polystat panels and one node would be represented by one hexagone: https://grafana.com/grafana/plugins/grafana-polystat-panel

**Comment by adejanovski** [comment]
Fixed by upgrading docker container version

**Comment by arodrime** [comment]
There is a little bit more here, that I have locally and will push here, before we deprecate this project in favour of MCAC.

**Comment by arodrime** [comment]
This was moved to [MCAC](https://github.com/datastax/metric-collector-for-apache-cassandra)
