### ISSUE TITLE
Make the setup easier adding an agent/script to do the setup of the nodes

### ISSUE THREAD

**Issue by arodrime** [thelastpickle/tlp-dashboards#7]
Here the idea is to simplify the setup of the dashboards by making available a script that could run on all the nodes to do the necessary setup (install exporters, configure them properly).

Users would be left with only Grafana / Prometeus to configure (and make sure they open the ports properly)

**Comment by alexott** [comment]
I'll adapt existing script for it...

**Comment by arodrime** [comment]
Hello @alexott. Is it something you are working on or planning to work on any time soon (it's just for us to track this work properly, no pressure :))

**Comment by alexott** [comment]
I'm still planning to work on it (maybe begin of next week).

**Comment by arodrime** [comment]
@alexott we're now maintaining [MCAC](https://github.com/datastax/metric-collector-for-apache-cassandra) instead. I'm closing this here, happy to see this issue moved over there if you're still willing to do that :).

**Comment by alexott** [comment]
Yep, I'll move it to MCAC...
