### ISSUE TITLE
Add a cassandra-reaper dashboard 

### ISSUE THREAD

**Issue by rzvoncek** [thelastpickle/tlp-dashboards#8]

**Comment by therb1** [comment]
Make a dashboard with this metric is realy hard.
when you have metrics like this:

io\_cassandrareaper\_service\_SegmentRunner\_repairing\_null\_**bigclustername**\_bigkeyspace
com\_datastax\_driver\_core\_Cluster\_**big\_cluster\_name**\_authentication\_errors

or

io\_cassandrareaper\_jmx\_JmxConnectionFactory\_connections\_**10x218x10x10**_1234_
io\_cassandrareaper\_jmx\_JmxProxyImpl\_cobrowsingtransitcas\_**10x218x10x191**\_repairStatusHandlers
io\_cassandrareaper\_service\_SegmentRunner\_abort\_**10\_218\_10\_10**
org\_eclipse\_jetty\_server\_HttpConnectionFactory\_0\_0\_0\_0\__8080_\_connections

@rzvoncek How do you plane work with this metrics without prometheus metric_relabel_configs?
I think a number of people, like me, for example, have no way to change the configuration of the prometheus

**Comment by rzvoncek** [comment]
Hi @therb1 , we know the metrics Reaper exposes have their nuances and limitations. We've done very little to tweak them, mostly because when metrics get pulled, it's usually the puller who has to process them. This makes life easier for us, because we don't need to make Reaper support every metric format out there (which is not feasible, really). The disadvantage is, of course, there are still cases like yours.

To answer your questions about plans. Metrics is not something that was in the initial Reaper. It's something we're adding incrementally. We had nothing, now we have the Prometheus endpoint, and there were talks over at [ASF Reaper Slack](https://the-asf.slack.com/archives/C010YBGLBF1) to add a DataDog one.

So it might be the time for another iteration on metrics to make the experience one bit better. But that deserves a dedicated issue (at least). And as always, we're always happy to accept help :)
